### ISSUE TITLE
`ips_disallow` is not used anywhere

### ISSUE THREAD

**Issue by BarakBD-Globality** [trussworks/terraform-aws-waf#7]
`ips_disallow` is not used anywhere - are you missing code?

**Comment by dynamike** [comment]
Thanks for the issue. At this point in time that `ips_disallow` is not being used due to a limitation around Terraform 0.11 not supporting dynamic blocks. See https://github.com/trussworks/terraform-aws-waf/pull/5 

So we currently manage the IP list outside of terraform. Looking forward to 0.12, we are looking to add support for IP lists back.

**Comment by BarakBD-Globality** [comment]
Terraform 12 is available, is it just a matter of upgrading the code?
Our upgrade was not too bad using their built-in `upgrade` command.
